/**
 * Mirror of pkg/manifest/manifest.go — AUTO-GENERATED via tygo.
 * Re-generate with: pnpm codegen (runs `go run github.com/gzuidhof/tygo generate`).
 * Do NOT hand-edit the Manifest types below; edit manifest.go and regenerate.
 */

export { APIVersion as METACORE_API_VERSION } from "./generated/manifest";

export type {
  Manifest,
  Module,
  NavGroup,
  NavItem,
  FrontendSpec,
  BackendSpec,
  Capability,
  Permission,
  SettingDef,
  Option,
  ToolDef,
  ToolInputParam,
  ActionDef,
  FieldDef,
  HookDef,
  HookTarget,
  ModelExtension,
  ModelDefinition,
  ColumnDef,
  Signature,
} from "./generated/manifest";

// CapabilityKind is a convenience union not present in Go (Go uses plain string).
export type CapabilityKind =
  | "db:read"
  | "db:write"
  | "http:fetch"
  | "event:emit"
  | "event:subscribe";

// Installation is a runtime record managed by the kernel host — not part of
// the manifest contract, so it is not generated by tygo.
export interface Installation {
  id: string;
  organization_id: string;
  addon_key: string;
  version: string;
  status: "enabled" | "disabled";
  source: "compiled" | "bundle" | "federated";
  settings: Record<string, unknown>;
  installed_at: string;
  enabled_at?: string;
  disabled_at?: string;
}
