package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	v3 "github.com/asteby/metacore-kernel/manifest/v3"
)

// cmdInit scaffolds a new addon directory emitting a Module Contract v3
// manifest. The scaffold ships one model, one wasm-backed action and a
// federated frontend so `metacore validate <key>` passes against the strict v3
// schema out of the box. The action's handler.function ("MarkDone") is the
// wasm export the compiled module must ship — `metacore compile-wasm` writes
// backend/backend.wasm later.
func cmdInit(args []string) error {
	fs := flag.NewFlagSet("init", flag.ExitOnError)
	_ = fs.Parse(args)
	if fs.NArg() < 1 {
		return fmt.Errorf("init: missing <key>")
	}
	key := fs.Arg(0)
	title := strings.Title(key) //nolint:staticcheck
	model := key + "_items"

	def := float64(0)
	m := &v3.Manifest{
		APIVersion: v3.APIVersion,
		Kind:       v3.KindAddon,
		Metadata: v3.Metadata{
			Key:         key,
			Name:        title,
			Description: "Generated by metacore init",
			Version:     "0.1.0",
			Category:    "utility",
			Icon:        &v3.Icon{Type: "lucide", Slug: "Package", Color: "#6366F1"},
			Author:      "you@example.com",
			License:     "MIT",
		},
		Compatibility: v3.Compatibility{
			Requires: []v3.Requirement{
				{Key: "kernel", Version: ">=3.0.0 <4.0.0"},
			},
		},
		Tenancy: &v3.Tenancy{Isolation: "shared", RLSColumn: "organization_id"},
		Capabilities: []v3.Capability{
			{Kind: "db:read", Target: "addon_" + key + ".*", Reason: "Read the addon's own rows."},
			{Kind: "db:write", Target: "addon_" + key + ".*", Reason: "Persist the addon's rows."},
		},
		Models: []v3.Model{
			{
				Key:   "Item",
				Table: model,
				Label: title + " items",
				Columns: []v3.Column{
					{Name: "id", Type: "uuid", PrimaryKey: true, Default: "gen_random_uuid()"},
					{Name: "organization_id", Type: "uuid", NotNull: true},
					{Name: "title", Type: "text", NotNull: true},
					{Name: "body", Type: "text"},
					{Name: "created_at", Type: "timestamptz", NotNull: true, Default: "now()"},
				},
			},
		},
		Contributions: &v3.Contributions{
			Navigation: []v3.NavGroup{
				{
					Title:  title,
					Icon:   "Package",
					Target: "sidebar.operations",
					Items: []v3.NavItem{
						{Title: title + " — Items", Model: "Item", Permission: key + ".item.read"},
					},
				},
			},
			Actions: []v3.Action{
				{
					Key:         "mark_done",
					Label:       title + ".action.mark_done",
					Icon:        "CheckCircle2",
					Handler:     v3.Handler{Type: "wasm", Function: "MarkDone"},
					TargetModel: "Item",
					Confirm:     true,
				},
			},
		},
		RBAC: &v3.RBAC{
			Permissions: []v3.PermissionDef{
				{Key: key + ".item.read", Label: "Read items"},
				{Key: key + ".item.write", Label: "Create/update/delete items"},
			},
		},
		// Frontend stays at the top level in v3 (kernel-internal federation
		// pointer). Format/expose/container mirror the v2 federation entry.
		Frontend: &v3.Frontend{
			Entry:     "/api/metacore/addons/" + key + "/frontend/remoteEntry.js",
			Format:    "federation",
			Expose:    "./plugin",
			Container: "metacore_" + key,
			Layout:    "shell",
		},
		Settings: []v3.Setting{
			{Key: "max_items", Type: "integer", Label: title + ".settings.max_items", Default: def, Required: false},
		},
	}

	mb, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}
	// Round-trip through the strict validator so a broken scaffold fails here
	// rather than at the author's first `metacore validate`.
	if err := v3.Validate(mb); err != nil {
		return fmt.Errorf("scaffold would be invalid: %w", err)
	}

	if err := os.MkdirAll(filepath.Join(key, "migrations"), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(key, "frontend", "src"), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(key, "manifest.json"), mb, 0o644); err != nil {
		return err
	}

	initSQL := fmt.Sprintf(`-- Initial schema for addon %q.
-- The host installs this under the isolated schema addon_%s.
CREATE TABLE IF NOT EXISTS %s (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  title           text NOT NULL,
  body            text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
`, key, key, model)
	if err := os.WriteFile(filepath.Join(key, "migrations", "0001_init.sql"), []byte(initSQL), 0o644); err != nil {
		return err
	}

	pluginStub := fmt.Sprintf(`// Federated entry for addon %q.
// Exposed as "./plugin" per manifest.frontend.expose.
export default {
  key: %q,
  register(ctx) {
    // ctx.registerRoute("/m/%s", () => <div>Hello from %s</div>);
  },
};
`, key, key, key, key)
	if err := os.WriteFile(filepath.Join(key, "frontend", "src", "plugin.tsx"), []byte(pluginStub), 0o644); err != nil {
		return err
	}

	readme := fmt.Sprintf("# %s\n\nAddon scaffolded by `metacore init` (Module Contract v3).\n", key)
	if err := os.WriteFile(filepath.Join(key, "README.md"), []byte(readme), 0o644); err != nil {
		return err
	}
	fmt.Printf("scaffolded ./%s (key=%s version=%s, apiVersion=%s)\n", key, key, m.Metadata.Version, v3.APIVersion)
	return nil
}
